[project]
name = "my-rv-project"
r_version = "4.5"

repositories = [
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
]

dependencies = [
    "IRkernel",
    "languageserver",
    "rmarkdown",
    "knitr",
    "ggplot2",
    "swirl",
]